### ISSUE TITLE
运行playbook总是提示inspur_sdk没有安装

### ISSUE THREAD

**Issue by bestsiyue** [ispim/inspur.ispim#40]
python：3.9.7
ansible-core： 2.15.12

使用如下playbook测试，总是会报错inspur_sdk must be installed to use this module。我的inspursmsdk也是安装的，ipmitool也已经安装，请问大概是什么问题。

```
- name: CPU test
  hosts: ism
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "Get cpu information"
    inspur.ispim.cpu_info:
      provider: "{{ ism }}"
```

![image](https://github.com/user-attachments/assets/97f1e71d-12af-48fc-abe7-e0360f02d018)

![image](https://github.com/user-attachments/assets/144ef425-24f6-46c8-810c-d638a2af6897)
